config/routes.rb
Rails.application.routes.draw do

  get '/create_message' => 'team_members#create_message'
  post '/create_message' => 'team_members#send_message'
  resources :team_members
  resources :duk
  resources :admins

  get 'site/learnyourwords', :path => 'index'
  get 'site/benefits', :path => 'benefits'
  get 'site/download', :path => 'download'
  get 'site/download_app_win' => 'site#download_app_win', as: :download_app_win
  get 'site/download_app_mac' => 'site#download_app_mac', as: :download_app_mac
  get 'site/blog', :path => 'blog'
  get 'site/contact', :path => 'contact'
  post '/contact' => 'site#contact_send_email'

  get 'admin' => 'sessions#new', as: :admin_login	#sign in,
  post 'admin' => 'sessions#create'
  delete 'logout' => 'sessions#destroy' #log out

  get 'admin/signup' => 'admins#new', as: :admin_signup #sign up

  get 'duks' => 'duk#new'
  post 'duks' => 'duk#create'

  root to: 'site#learnyourwords'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

  validates :username,
          presence: true
end

app/models/duk.rb
class Duk < ActiveRecord::Base
  validates :query,
    presence: true
  validates :answer,
    presence: true,
    length: { maximum: 600 }
end

app/models/stat.rb
class Stat < ActiveRecord::Base
	validates :downloads,
		presence: true
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  validates :name,
			  presence: true,
			  length: { minimum: 6},
			  uniqueness: true
	validates :image,
			  presence: true
	validates :quote,
			  presence: true
  validates :email,
        presence: true,
        uniqueness: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def new
		@admin = Admin.new
	end

  def edit
	end

  def show
  end

	def create
		@admin = Admin.new(admin_params)
		if @admin.save
			session[:admin_id] = @admin.id
			redirect_to '/admin'
		else
			redirect_to '/admin/signup'
		end
	end

  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

	private
	def admin_params
		params.require(:admin).permit(:username, :email, :image, :password)
	end
  def set_admin
    @admin = Admin.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_admin, :require_admin

	def current_admin
	  @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
	end

	def require_admin
		redirect_to '/admin' unless current_admin
	end
end

app/controllers/duk_controller.rb
class DukController < ApplicationController
  before_action :set_duk, only: [:show, :edit, :update, :destroy]

  def index
    @duks = Duk.all
  end

  def new
    @duk = Duk.new
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if @duk.update(duk_params)
        format.html { redirect_to @duk, notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @duk }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @duk = Duk.new(duk_params)

    respond_to do |format|
      if @duk.save
        format.html { redirect_to '/duk', notice: 'Duk was successfully created.' }
        format.json { render :show, status: :created, location: @duk }
      else
        format.html { render :new }
        format.json { render json: @duk.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @duk.destroy
    respond_to do |format|
      format.html { redirect_to '/duk', notice: 'Duk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duk
      @duk = Duk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duk_params
      params.require(:duk).permit(:query, :answer, :link)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	end

  def destroy
    #@session = Session.find(params[:admin_id])
    #@session.destroy
		session[:admin_id] = nil
		redirect_to '/'
	end

	def create
		@admin = Admin.find_by_username(params[:session][:username])
		if @admin && @admin.authenticate(params[:session][:password])
			session[:admin_id] = @admin.id
			redirect_to(:back)
		else
			flash.now.alert = "Invalid username or password"
			redirect_to(:back)
		end
	end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :set_stat, only: [:download, :download_app_win, :download_app_mac]
  def home
  end

  def benefits
  end

  def download
  end

  def download_app_win
    count = @stat.downloads+1
    @stat.update_attributes(downloads: count)
	   send_file Rails.root.join('app', 'assets', 'downloads', 'LearnWords.zip')
  end

  def download_app_mac
    count = @stat.downloads+1
    @stat.update_attributes(downloads: count)
    send_file Rails.root.join('app', 'assets', 'downloads', 'LearnWords.dmg'), type: "application/dmg"
  end

  def contact
  end

  def blog
  end

  def contact_send_email
  	@name = params[:name]
  	@email = params[:email]
  	@comment = params[:comment]
  	ContactMailer.send_message(@name, @email, @comment).deliver_now
  end

  private
    def set_stat
      @stat = Stat.find(1)
    end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render :show, status: :created, location: @team_member }
      else
        format.html { render :new }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_url, notice: 'Team member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_message
  end

  def send_message
    @team_members = TeamMember.all
    @admin = Admin.find(session[:admin_id])
  	@message = params[:message]
  	TeamMembersMailer.send_message(@admin, @team_members, @message).deliver_now
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.require(:team_member).permit(:name, :job_title, :phone, :location, :image, :quote, :email)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/duk_helper.rb
module DukHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li class="error"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "submit" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Update Admin</h1>
			<%= link_to 'Back', admin_login_path, class: "admin_button go_back" %>
		  <%= render 'form' %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/admins/new.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Register</h1>
			<%= link_to 'Back', admin_login_path, class: "admin_button go_back" %>
			<%= render 'form' %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/admins/show.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<p id="notice"><%= notice %></p>
			<%= image_tag(@admin.image) %>
			<h3>
			  <%= @admin.username %>
			</h3>
			<p>
			  <%= @admin.email %>
			</p>
			<div class="buttons">
				<%= link_to 'Update Admin', edit_admin_path(@admin), class: "admin_button" %>
				<%= link_to 'Back', admin_login_path, class: "admin_button" %>
			</div>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/duk/_form.html.erb
<%= form_for(@duk) do |f| %>
  <% if @duk.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @duk.errors.full_messages.each do |message| %>
        <li class="error"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %>
    <%= f.text_area(:query, size: "35x2")  %>
  </div>
  <div class="field">
    <%= f.label :answer %>
    <%= f.text_area(:answer, size: "35x7", maxlength: 600) %>
  </div>
  <div class="field">
    <%= f.label :answer %>
    <%= f.text_field(:link, size: "35x7", maxlength: 600) %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "submit" %>
  </div>
<% end %>

app/views/duk/edit.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Update Team Member</h1>
			<%= link_to 'Back', admin_login_path, class: "admin_button go_back" %>
			<%= form_for(@duk) do |f| %>
			  <% if @duk.errors.any? %>
			    <div id="error_explanation">
			      <ul>
			      <% @duk.errors.full_messages.each do |message| %>
			        <li class="error"><%= message %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>

       <%=  render 'form' %>
			<% end %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/duk/index.html.erb
<% content_for :title, "LearnWords - Frequently Asked Questions" %>
<% content_for :meta, "Ask your own questions or see the answers for the most
common ones." %>
<section class="duk_page jumbotron">
	<div class="container">
		<h1>F.A.Q</h1>
		<div class="duks">
			<% @duks.each do |duk| %>
				<div class="duk center col-md-3 col-sm-8">
					<% if current_admin %>
						<%= link_to image_tag("delete_duk"), duk, method: :delete, class: "duk_buttons"%>
						<%= link_to image_tag("edit_duk"), edit_duk_path(duk), class: "duk_buttons" %>
					<% end %>
					<h3 class="query"><%= duk.query %></h3>
					<div class="answer">
						<h6 class="text-answer"><%= duk.answer %></h6>
						<% if duk.link != nil && duk.link != "" %>
							<a class="link" target="_blank" href="<%= duk.link %>">Link</a>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</section>

app/views/duk/new.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Add New FAQ</h1>
			<%= link_to 'Back', admin_login_path, class: "admin_button go_back" %>
			<%= render 'form' %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/duk/show.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
      <div class="show_duk" %>
  			<h4 class="query">
  			  <%= @duk.query%>
  			</h3>
  			<p class="answer">
  			  <%= @duk.answer %>
  			</p>
      </div>
			<div class="buttons">
        <%= link_to 'Show all FAQs', duk_index_path, class: "admin_button" %>
				<%= link_to 'Update FAQs', edit_duk_path(@duk), class: "admin_button" %>
				<%= link_to 'Back', admin_login_path, class: "admin_button" %>
			</div>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/layouts/application.html.erb
<%# encoding: utf-8 %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= javascript_include_tag 'application' %>


  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag "http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" %>
  <%= stylesheet_link_tag "style" %>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="<%= yield(:meta) %>">
  <%= favicon_link_tag 'favicon.png' %>

  <!-- Include all compiled plugins (below), or include individual files as needed -->
  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-72783854-1', 'auto');
    ga('send', 'pageview');
  </script>
  <%= csrf_meta_tag %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<img src="/assets/menu.png" />
		  </button>
		  <!-- <a class="navbar-brand logo" href="site_home_path"></a> -->
		  <%= link_to "", site_learnyourwords_path,  { class: "navbar-brand logo" } %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		  <ul class="nav navbar-nav navbar-links">

			<li><a href="<%= site_benefits_url %>"><img src="/assets/features.png" ><p>Features</p></a></li>
			<li><a href="<%= site_download_url %>"><img src="/assets/download.png" ><p>Download</p></a></li>
			<li><a href="<%= site_contact_url %>"><img src="/assets/contacts.png" ><p>Contacts</p></a></li>
		  </ul>
		  <ul class="nav navbar-nav navbar-right social">
			<li class="hidden-xs"><a href="http://www.facebook.com/Serapinas"><img src="/assets/facebook_navbar.png" /></a></li>
			<li class="hidden-xs"><a href="https://twitter.com/M_Serapinas"><img src="/assets/twitter_navbar.png" /></a></li>
			<li class="hidden-xs"><a href="http://lt.linkedin.com/pub/mantas-serapinas/8a/961/760"><img src="/assets/linkedin_navbar.png" /></a></li>
		  </ul>
		</div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<%= yield %>

	<div class="footer">
		<div class="container">
			<div class="row info">
				<div class="col-md-4">
					<h3>Apie</h3>
					<ul>
						<li><a href="benefits.html">Features</a></li>
						<li><a href="contact.html">Contacts</a></li>
						<li><%= link_to "Our Team", team_members_path %></li>
					</ul>
				</div>
				<div class="col-md-4">
					<h3>Pagalba</h3>
					<ul>
						<li><%= link_to "F.A.Q", duk_index_path %></li>
						<li><a href="blog.html">Blog</a></li>
					</ul>
				</div>
				<div class="col-md-4">
					<h3>Join our Team </h3>
					<p>M.Serapinas@gmail.com</p>

          <%= link_to "Admin", admin_login_path, { class: "admin_login"} %>
				</div>
			</div>
			<div class="row rights">
				<p>&#169;2016 LearnYourWords.com - All rights reserved.</p>
			</div>
		</div>
	</div>

</body>
</html>

app/views/layouts/team_members_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h2>You've got a new mail from Admin, <%= @admin.name %></h2>
    <h4>The message is:<h4>
    <p><%= simple_format(@message) %></p>
    <p style="font-weight: bold"><%= @admin.email %></p>
  </body>
</html>

app/views/layouts/team_members_mailer.text.erb
<%= yield %>

app/views/site/blog.html.erb
<% content_for :title, "LearnWords - Oops!" %>
<% content_for :meta, "In progress! Soon to be our new blog!" %>
<div class="blog jumbotron">
	<h1>Oops! Currently this site is Under Construction</h1>
</div>

app/views/site/contact.html.erb
<% content_for :title, "LearnWords - Contact" %>
<% content_for :meta, "Contact us. We are happy to help on your queries. Join our
team. Improve our product by giving us feedback. Report bugs here." %>
<div class="contact-content jumbotron row">
	<div class="col-md-1 hidden-xs">
	</div>
	<div class="col-md-6 get_in_touch">
		<h1>Contact Us</h1>
		<p>
			We are friendly and easily approachable team.
			If you have any questions, don't be shy - ask, we are happy to help.
			Give us a call or email us. Contact us on Twitter or just use the form
			below.
		</p>
		<div class="contact_details">
			<div class="container">
				<div class="detail">
					<img src="/assets/phone.png"/><p>+447783008354</p>
				</div>
				<div class="detail">
					<img src="/assets/email.png"/><p>M.Serapinas@gmail.com</p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-4 right">
		<%= form_tag(contact_path, class: 'response form-horizontal') do %>
			<h2 class="contact-title">Send Message</h2>
			<div class="form-group">
			  <label class="control-label col-sm-4" for="name">Name</label>
			  <div class="col-sm-8">
				<%= text_field_tag 'name', nil, placeholder: 'Name', class: 'form-control', autocomplete: 'on' %>
			  </div>
			</div>

			<div class="form-group">
			  <label class="control-label col-sm-4" for="email">Email</label>
			  <div class="col-sm-8">
				<%= text_field_tag 'email', nil, placeholder: 'Email', class: 'form-control', autocomplete: 'on' %>
			  </div>
			</div>

			<div class="form-group">
			  <label class="control-label col-sm-4" for="comment">Message</label>
			  <div class="col-sm-8">
				<%= text_area_tag 'comment', nil, placeholder: 'Your comment', class: 'form-control', autocomplete: 'on', rows: '6' %>
			  </div>
			</div>
			<div class="button-holder">
				<%= submit_tag 'Send', class: 'submit' %>
			</div>
		<% end %>
	</div>
</div>

app/views/site/contact_send_email.html.erb
<% content_for :title, "LearnWords - Contact" %>
<div class="contact-content row jumbotron">
	<div class="col-md-1 hidden-xs">
	</div>
	<div class="col-md-6 get_in_touch">
		<h1>Contact Us</h1>
		<p>
			We are friendly and easily approachable team.
			If you have any questions, don't be shy - ask, we are happy to help.
			Give us a call or email us. Contact us on Twitter or just use the form
			below.
		</p>
		<div class="contact_details">
			<div class="container">
				<div class="detail">
					<img src="/assets/phone.png"/><p>+447783008354</p>
				</div>
				<div class="detail">
					<img src="/assets/email.png"/><p>M.Serapinas@gmail.com</p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-5 right">
		<%= form_tag(site_contact_path, class: 'response form-horizontal', authenticity_token: true) do %>
			<h2 class="contact-title">Send Message</h2>
			<div>
				<p>Thank you! We will contact you soon.</p>
			</div>
		<% end %>
	</div>
</div>

app/views/site/download.html.erb
<% content_for :title, "LearnWords - Download" %>
<% content_for :meta, "Download LearnWords application. Available on two platforms
 Mac OS X and Windows. Free." %>
<div class="download jumbotron">
	<div class="container">
		<h1 class="title">LearnWords</h1>
		<div class="row">
			<div class="col-md-1 col-sm-0 col-lg-1"></div>
			<div class="col-md-5 col-sm-0 col-lg-5 left hidden-xs">
				<img src="/assets/product.png" />
			</div>
			<div class="col-md-1 col-sm-0 col-lg-1"></div>
			<div class="col-md-4 col-sm-12 col-lg-4 right">
				<div class="downloadDescription">
					<ul>
						<li>Easy to Use</li>
						<li>New Words Everyday</li>
						<li>Just a Few Mintues Per Day</li>
						<li>No Need of Connection to the Internet</li>
					</ul>
				</div>
				<div class="downloadButtons">
					<%= link_to "Download | Windows 7", download_app_win_path, id: "download_win" %>
					<%= link_to "Download | Mac OS X", download_app_mac_path, id: "download_mac" %>
				</div>
				<div class="downloadedTimes">
					<p>Learnwords downloaded <%= @stat.downloads %> times!</p>
				</div>
			</div>
			<div class="col-md-1 col-sm-0 col-lg-1"></div>
		</div>
	</div>
</div>

app/views/site/home.html.erb
<header class="header jumbotron">
	<div class="container">
		<h1>LearnWords</h1>
		<h2>Learn new English words without wasting lots of time and energy</h2>
		<p class="present">
				Don't waste your time trying to learn words by hard. <br>
				Just download our application and learn words without much effort.<br>
				Learning new words with LearnWords Application is simple and fun!
		</p>
		<div class="center">
			<%= link_to "Download", site_download_path %>
		</div>
	</div>
</header>

app/views/site/learnyourwords.html.erb
<% content_for :title, "LearnWords - Learning Made Easy" %>
<% content_for :meta, "LearnWords makes learning new English or Lithuanian words
easy. Our app is free. Learnwords - simple and fun way to learn a language." %>
<header class="header jumbotron">
	<div class="container">
		<h1>LearnWords</h1>
		<h2>Learn new English words without wasting lots of time and energy</h2>
		<p class="present">
				Don't waste your time trying to learn words by heart. <br>
				Just download our application and learn words without much effort.<br>
				Learning new words with LearnWords Application is simple and fun!
		</p>
		<div class="center">
			<%= link_to "Download", site_download_path %>
		</div>
	</div>
</header>

app/views/team_members/_form.html.erb
<%= form_for(@team_member) do |f| %>
  <% if @team_member.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @team_member.errors.full_messages.each do |message| %>
        <li class="error">- <%= message %>!</li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :job_title %>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :quote, "*Quote" %>
    <%= f.text_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "submit" %>
  </div>
<% end %>

app/views/team_members/create_message.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Send Message</h1>
			<%= link_to 'Back', admin_login_path, class: "admin_button go_back" %>
			<%= form_tag(create_message_path) do %>
					<label class="control-label" for="comment">Message</label>
					<%= text_area_tag 'message', nil, placeholder: 'Your message', class: 'form-control', autocomplete: 'on', rows: '8' %>
				<div class="button-holder">
					<%= submit_tag 'Send', class: 'submit' %>
				</div>
			<% end %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/team_members/edit.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Atnaujinti komandos narį</h1>
			<%= link_to 'Back', @team_member, class: "admin_button go_back" %>
			<%= render 'form' %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/team_members/new.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Add New Member</h1>
			<%= link_to 'Back', admin_login_path, class: "admin_button go_back" %>
			<%= render 'form' %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/team_members/send_message.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<h1>Message sent</h1>
			<%= link_to 'Back', @team_member, class: "admin_button go_back" %>
			<%= form_tag(create_message_path) do %>
				<div>
					<p class="message_sent">Thank you! We will contact you soon.</p>
				</div>
			<% end %>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>

app/views/team_members/show.html.erb
<% if current_admin %>
	<div class="admin_panel jumbotron">
		<div class="container">
			<p id="notice"><%= notice %></p>
			<%= image_tag(@team_member.image) %>
			<h3>
			  <%= @team_member.name %>
			</h3>
			<p>
			  <%= @team_member.job_title %>
			</p>
			<p>
			  <%= @team_member.phone %>
			</p>
			<p>
			  <%= @team_member.location %>
			</p>
			<p class="quote">
			  <%= @team_member.quote %>
			</p>
			<div class="buttons">
				<%= link_to 'Delete Member', team_members_path, action: "delete", class: "admin_button" %>
				<%= link_to 'Update Member', edit_team_member_path(@team_member), class: "admin_button" %>
				<%= link_to 'Back', admin_login_path, class: "admin_button" %>
			</div>
		</div>
	</div>
<% else %>
	<% require_admin %>
<% end %>